swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /personas/:
    put:
      tags:
      - personas
      description: Actualizar datos de persona
      operationId: SgaTercerosController.ActualizarPersona
      parameters:
      - in: body
        name: body
        description: body for Actualizar datos de persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
    post:
      tags:
      - personas
      description: Guardar Persona
      operationId: SgaTercerosController.PostPersona
      parameters:
      - in: body
        name: body
        description: body for Guardar Persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/{tercero_id}:
    get:
      tags:
      - personas
      description: get ConsultaPersona by id
      operationId: SgaTercerosController.ConsultarPersona
      parameters:
      - in: path
        name: tercero_id
        description: Id del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/complementarios:
    get:
      tags:
      - personas
      description: get ConsultarDatosComplementarios by id
      operationId: SgaTercerosController.ConsultarDatosComplementarios
      parameters:
      - in: path
        name: tercero_id
        description: Id del ente
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/contacto:
    get:
      tags:
      - personas
      description: get ConsultarDatosContacto by id
      operationId: SgaTercerosController.ConsultarDatosContacto
      parameters:
      - in: path
        name: tercero_id
        description: Id del Tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/familiar:
    get:
      tags:
      - personas
      description: get ConsultarDatosFamiliar by id
      operationId: SgaTercerosController.ConsultarDatosFamiliar
      parameters:
      - in: path
        name: tercero_id
        description: Id del Tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/formacion-pregrado:
    get:
      tags:
      - personas
      description: get ConsultarDatosFormacionPregrado by id
      operationId: SgaTercerosController.ConsultarDatosFormacionPregrado
      parameters:
      - in: path
        name: tercero_id
        description: Id del Tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/{tercero_id}/info-solicitante:
    get:
      tags:
      - personas
      description: get ConsultarInfoSolicitante by id
      operationId: SgaTercerosController.ConsultarInfoSolicitante
      parameters:
      - in: path
        name: tercero_id
        description: Id del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/autores:
    post:
      tags:
      - personas
      description: Guardar autor
      operationId: SgaTercerosController.PostAutor
      parameters:
      - in: body
        name: body
        description: body for Guardar autor content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/complementarios:
    put:
      tags:
      - personas
      description: ActualizarDatosComplementarios
      operationId: SgaTercerosController.ActualizarDatosComplementarios
      parameters:
      - in: body
        name: body
        description: body for Actualizar los datos complementarios content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
    post:
      tags:
      - personas
      description: Guardar Datos Complementarios Persona
      operationId: SgaTercerosController.GuardarDatosComplementarios
      parameters:
      - in: body
        name: body
        description: body for Guardar Datos Complementarios Persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/complementarios-par-academico:
    post:
      tags:
      - personas
      description: Guardar Datos Complementarios Persona ParAcademico
      operationId: SgaTercerosController.GuardarDatosComplementariosParAcademico
      parameters:
      - in: body
        name: body
        description: body for Guardar Datos Complementarios Persona content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/contacto:
    post:
      tags:
      - personas
      description: Guardar DatosContacto
      operationId: SgaTercerosController.PostrDatosContacto
      parameters:
      - in: body
        name: body
        description: body for Guardar DatosContacto content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "201":
          description: '{int}'
        "400":
          description: the request contains incorrect syntax
  /personas/existencia/{numeroDocumento}:
    get:
      tags:
      - personas
      description: get ConsultarExistenciaPersona by NumeroIdentificacion
      operationId: SgaTercerosController.ConsultarExistenciaPersona
      parameters:
      - in: path
        name: numeroDocumento
        description: numero documento del tercero
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{}'
        "404":
          description: not found resource
  /personas/info-familiar:
    put:
      tags:
      - personas
      description: Actualiza la informacion familiar del tercero
      operationId: SgaTercerosController.ActualizarInfoFamiliar
      parameters:
      - in: body
        name: body
        description: body for Actualizar la info familiar del tercero content
        required: true
        schema:
          $ref: '#/definitions/{}'
      responses:
        "200":
          description: '{}'
        "403":
          description: body is empty
  /personas/nit:
    get:
      tags:
      - personas
      description: Retorna una lista de terceros con su NIT y nombre completo.
      operationId: SgaTercerosController.ObtenerTerceroConNIT
      responses:
        "200":
          description: '"Lista de terceros con NIT, nombre completo y label correspondiente."'
          schema:
            type: array
            items:
              $ref: '#/definitions/TerceroConNIT'
        "400":
          description: '"bad request" en caso de una solicitud incorrecta o problemas en la consulta.'
  /propiedad/:
    get:
      tags:
      - propiedad
      description: List the Propiedades types that can be used to gather Propiedades by {propiedad}
      operationId: PropiedadesController.GetAll
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              type: string
  /propiedad/{propiedad}/{idTercero}:
    get:
      tags:
      - propiedad
      description: get Dependencia with the specified {idTercero}
      operationId: PropiedadesController.GetAll
      parameters:
      - in: path
        name: propiedad
        description: type propiedad of Terceros
        required: true
        type: string
      - in: path
        name: idTercero
        description: Tercero ID from terceros_crud
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/map[string]interface{}'
        "500":
          description: Internal Error
        "501":
          description: '{user} Not Implemented'
        "502":
          description: Error with external API
  /tipo/:
    get:
      tags:
      - tipo
      description: List the Tercero types that can be used to gather Terceros by {tipo}
      operationId: TiposController.GetAll
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              type: string
  /tipo/{tipo}:
    get:
      tags:
      - tipo
      description: get Terceros with the specified {tipo}
      operationId: TiposController.GetAll
      parameters:
      - in: path
        name: tipo
        description: Tercero type available from /tipo/
        required: true
        type: string
      - in: query
        name: query
        description: Query param
        type: string
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/map[string]interface{}'
        "500":
          description: Internal Error
        "501":
          description: '{tipo} Not Implemented'
        "502":
          description: Error with external API
  /tipo/{tipo}/{id}:
    get:
      tags:
      - tipo
      description: get Terceros with the specified {tipo} and {id} of a record in terceros table from Terceros CRUD API
      operationId: TiposController.GetAll
      parameters:
      - in: path
        name: tipo
        description: Tercero type available from /tipo/
        required: true
        type: string
      - in: path
        name: id
        description: Tercero ID. Must be positive when specified
        required: true
        type: integer
        format: int32
      responses:
        "200":
          description: ""
          schema:
            type: array
            items:
              $ref: '#/definitions/map[string]interface{}'
        "400":
          description: Wrong ID
        "404":
          description: ID with {tipo} Not Found
        "500":
          description: Internal Error
        "501":
          description: '{tipo} Not Implemented'
        "502":
          description: Error with external API
definitions:
  '{}':
    title: '{}'
    type: object
  TerceroConNIT:
    title: TerceroConNIT
    type: object
  map[string]interface{}:
    title: map[string]interface{}
    type: object
tags:
- name: tipo
  description: |
    TercerosController operations for Terceros
- name: propiedad
  description: |
    PropiedadesController operations for propiedades
- name: personas
  description: |
    SgaTercerosController operations for Tercero
