appname = terceros_mid
httpport = ${TERCEROS_MID_PORT}
runmode = ${TERCEROS_MID_RUN_MODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}

InscripcionService = ${INSCRIPCION_SERVICE}
OikosService = ${OIKOS_SERVICE}
ParametroService = ${PARAMETRO_SERVICE}
ProyectoAcademicoService = ${PROYECTO_SERVICE}
TercerosService = ${TERCEROS_SERVICE}
UbicacionesService = ${UBICACIONES_SERVICE}
