appname = terceros_mid
httpport = ${TERCEROS_MID_PORT}
runmode = ${TERCEROS_MID_RUN_MODE}
autorender = false
copyrequestbody = true
EnableDocs = true


ConsultarReciboJbpmService = ${CONSULTAR_RECIBO_JBPM_SERVICE}
DescuentoAcademicoService = ${DESCUENTO_ACADEMICO_SERVICE}
EventoService = ${EVENTOS_SERVICE}
ExperienciaLaboralService = ${EXPERIENCIA_LABORAL_SERVICE}
GenerarReciboJbpmService = ${GENERAR_RECIBO_JBPM_SERVICE}
InscripcionService = ${INSCRIPCION_SERVICE}
logPath= ${SGA_MID_LOG}
OikosService = ${OIKOS_SERVICE}
ParametroService = ${PARAMETRO_SERVICE}
ProduccionAcademicaService = ${PRODUCCION_ACADEMICA_SERVICE}
ProyectoAcademicoService = ${PROYECTO_SERVICE}
SolicitudDocenteService = ${SOLICITUD_DOCENTE_SERVICE}
StaticPath = ${SGA_MID_STATIC_PATH}
TercerosService = ${TERCEROS_SERVICE}
UbicacionesService = ${UBICACIONES_SERVICE}
